### ISSUE TITLE
Control two steppers

### ISSUE THREAD

**Issue by BeckElectronics** [cwi-dis/iotsaMotorServer#1]
Hello
First thank you for this great project, and share it.
I think it's possible to add a second stepper, but I'm a little lost. 
-> What can I do in the code to control two steppers ? 
Thank you so much. ;-)

**Comment by jackjansen** [comment]
You need to set `numMotors` to 2 (line 48) and then add the pin information for the second motor to `stepperMot` and `zeroDetectPin`, and an extra 0 to `motorLimit`.

*But*, and this is a large but: assuming you're using an ESP8266 you don't have enough hardware pins to drive two motors. You need 5 pins per motor (but you could conceivably do away with the zero-detect pin, then you need 4) and there are only 6 easily usable digital IO pins on the esp8266.

If you're using an ESP32 you should have more than enough GPIO pins, but then be warned that I've never used iotsaMotorServer on an ESP32 so there may be surprises...

**Comment by BeckElectronics** [comment]
Thank you for reply.
I've forgot to say I use the ESP12E with Lollin kit, it offer normaly 10 GPIO : 
[https://cdn.instructables.com/FPV/E4YC/IKLFP40J/FPVE4YCIKLFP40J.LARGE.jpg](url)

It's ok for `numMotors`  but, to set informations in `stepperMot` and `zeroDetectPin` I don't see how to do. 
I've seen this exemple in data on AccelStepper library of Airspayce website : 
[https://www.airspayce.com/mikem/arduino/AccelStepper/MultipleSteppers_8pde-example.html](url)
or this to use MultiStepper class : 
[https://www.airspayce.com/mikem/arduino/AccelStepper/MultiStepper_8pde-example.html](url)

My main problem is that in this exemples they use 
`AccelStepper stepper2(AccelStepper::FULL4WIRE, 6, 7, 8, 9);`
(in 1st airspayce link )
instead of
`AccelStepper stepperMot[numMotors]= {
  AccelStepper(AccelStepper::HALF4WIRE, motor1Pin1, motor1Pin3, motor1Pin2, motor1Pin4, true)
};`
in IotsaMotorServer code.
That's why maybe I don't undestand how to do.

Maybe I must to precise I want to control two steppers independantly ;-)
Thanks.

**Comment by jackjansen** [comment]
First of all: be careful with assuming 10 GPIO pins. Pins 0 and 2 have a special meaning during power up and reset. After that you can use them as outputs, so you may be okay with that. 1 and 3 have another issue: they are normally used for the UART. And if you want to use _iotsa_ it will initialise the UART early during startup, so you will have to disable that. 

Second, as to `zeroDetectPin`: it should be fairly easy to remove all references to it if you don't want to do zero detection. (In the code here it is connected to a microswitch that engages whenever the cable that the motor pulls up has reached its maximum, to forestall the motor trying to continue rolling up if the cable is at the end).

Third, as to the `stepperMot` initialisation: the arguments for the call to the `AccelStepper()` constructor depend on the actual motor you have and the driver IC you use. Check the library documentation (it is included in the _.h_ file, for example at <https://github.com/waspinator/AccelStepper/blob/master/src/AccelStepper.h>. And let me warn you that you're probably going to get things wrong a lot of times before you get it right (with at best the motor only doing _brp. brp. brp._ in stead of moving the way you want it). At least, I did:-)

Lastly, the way they initialise the `stepper2` variable in the example you quote and the way it is done in my code is simply two different C++ ways to do this (in slightly different situations). So something like

```
AccelStepper stepperMot[numMotors]= { 
  AccelStepper(AccelStepper::HALF4WIRE, 6, 7, 8, 9, true),
  AccelStepper(AccelStepper::HALF4WIRE, 10, 11, 12, 13, true)
};
```

(if one 4-wire half-step motor was connected to GPIO 6..9 and the other to GPIO 10..13) would work.

Actually, for experimentation I would suggest that you start with only _one_ stepper motor, using the existing code with `zeroDetectPin` removed. Then only when you get that working you worry about the second motor...

**Comment by BeckElectronics** [comment]
Okay I've successfully finis, it work good.
I've tried some pins, somes stay HIGH in first boot, but since first move they work normaly.

Thank you very much for the help,  and for taking the time to guide me :)
